# Default values for kyverno-policies.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

# policySets: defines the policy categories you can deploy.
# common policy set is always enabled and should be deployed
# to all environments/clusters.
# there is the ability to disable common policy deployment
# if needed by any reason.

policySets:
  common:
    enabled: true
    # namespace where the policies will be deployed
    namespace: policy
    # validationFailureAction can be Audit|Enforce by default run the common policy set as audit mode, variable moved to the policy level
    # checkLimits if set to false policy will only apply for resource request.
    # set it to true to make the policy checks limits.
    checkLimits: true
    forbid:
      category: "SRE Best Practices"
      severity: medium
      validationFailureAction: Audit
      exclude:
        any:
        - resources:
            kinds:
            - CronJob
            selector:
              matchLabels:
                kyverno-forbid-policy: skip
    hpa:
      category: "SRE Best Practices"
      severity: medium
      validationFailureAction: Audit
      exclude:
        any:
        - resources:
            kinds:
            - Deployment
            selector:
              matchLabels:
                app.kubernetes.io/instance: '*staging*'
        - resources:
            kinds:
            - Deployment
            selector:
              matchLabels:
                kyverno-hpa-policy: skip
    publicAccess:
      category: "Security Best Practices"
      severity: medium
      validationFailureAction: Audit
      exclude:
        any:
        - resources:
            kinds:
            - Ingress
            - Service
            selector:
              matchLabels:
                kyverno-public-access-policy: skip
    labels:
      category: "SRE Best Practices"
      severity: medium
      validationFailureAction: Audit
      exclude:
        any:
        - resources:
            kinds:
            - Deployment
            - CronJob
            selector:
              matchLabels:
                kyverno-labels-policy: skip
    labelsV2:
      category: "SRE Best Practices"
      severity: medium
      validationFailureAction: Audit
      exclude:
        any:
        - resources:
            kinds:
            - Deployment
            - CronJob
            selector:
              matchLabels:
                kyverno-labels-policy: skip
    probes:
      category: "SRE Best Practices"
      severity: medium
      validationFailureAction: Audit
      exclude:
        any:
        - resources:
            kinds:
            - Deployment
            selector:
              matchLabels:
                kyverno-probes-policy: skip
    resources:
      category: "SRE Best Practices"
      severity: high
      validationFailureAction: Audit
      exclude:
        any:
        - resources:
            kinds:
            - Deployment
            - DaemonSet
            - StatefulSet
            - CronJob
            selector:
              matchLabels:
                kyverno-resources-policy: skip
    securityContext:
      category: "Security Best Practices"
      severity: high
      validationFailureAction: Audit
      exclude:
        any:
        - resources:
            kinds:
            - Deployment
            - CronJob
            selector:
              matchLabels:
                kyverno-security-context-policy: skip
  # bellow is and example on how to add extra policy sets for other envs.
  # dev:
  #   enabled: true
  #   validationFailureAction: enforce
