# Default values for kyverno-policies.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

# policySets: defines the policy categories you can deploy.
# common policy set is always enabled and should be deployed
# to all environments/clusters.
# there is the ability to disable common policy deployment
# if needed by any reason.

policySets:
  common:
    enabled: true
    # by default run the common policy set as audit mode
    validationFailureAction: audit
    # enforceLimits if set to false policy will only apply for resource request.
    # set it to true to make the policy enforce request and limits.
    enforceLimits: false
  # bellow is and example on how to add extra policy sets for other envs.
  # dev:
  #   enabled: true
  #   validationFailureAction: enforce
