# Default values for kyverno-policies.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

# policySets: defines the policy categories you can deploy.
# common policy set is always enabled and should be deployed
# to all environments/clusters.
# there is the ability to disable common policy deployment
# if needed by any reason.

policySets:
  common:
    enabled: true
    # namespace where the policies will be deployed
    namespace: policy
    # validationFailureAction can be Audit|Enforce by default run the common policy set as audit mode
    validationFailureAction: Audit
    # checkLimits if set to false policy will only apply for resource request.
    # set it to true to make the policy checks limits.
    checkLimits: true
  # bellow is and example on how to add extra policy sets for other envs.
  # dev:
  #   enabled: true
  #   validationFailureAction: enforce
