# Default values for common.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Used for NODE_ENV and DD_ENV
environment: staging
# Required: GCP Project where this Release will be deployed
project: ""

image:
  repository: nginx
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

args: ""

# Add custom sidecar containers to main script runner
sidecars: []
# sidecars:
# - name: sidecar-1
#   image: alpine:latest
#   command: [sh, -c]
#   args: ["while true; do echo hello world!!!; sleep 10; done"]

serviceAccount:
  # Specify the name of the SA to use, defaults to workflows
  # You can use an already defined SA
  # If you are using a complete new SA, change the name and set true to create and addRBAC
  name: workflows
  # Specifies whether a service account should be created
  # This should be set to false if you are re-using an existing SA
  create: false
  # Adds the necesary RBAC roles for the SA, this needs to be used only once per SA
  # if you are using an SA originally created by a deployment with common chart, this should be set to true
  addRBAC: false

  # Annotations to add to the service account
  # Only if serviceAccount.create:true
  annotations: {}
  # IAM workload idenitity binding name
  # If not set and serviceAccount.create:true, a name is generated using Release.Name
  # If Release.Name is bigger than 30 characteres use this variable to overwrite it with something shorter to identify this workload
  # Only if serviceAccount.create:true
  workloadIdentitySA: ""


# You can add a cloudsql proxy template by enabling this option.
# This is similar to migrations detifnitions.
cloudsqlProxy:
  enabled: false
  port: "3306"
  instanceConnectionName: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 200m
  #   memory: 256Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Used for DD_TRACE_AGENT_HOSTNAME on DD APM/Node.js potentially can be used with logger vars too
apm:
  enabled: false
  # If datadogEnvironment is not defined we use variable environment as default
  datadogEnvironment: ""

# Default Logger and DD variables are defined here: https://github.com/dave-inc/charts/blob/master/common/templates/deployment.yaml
# Custom env variables are defined here and will be populated via Deployment's ConfigMap
env: {}

# ConfigMap
# The configMapName is optional, If not set, a name is generated using Release.Name
configMapName: ""
existingConfigMapName: ""

# To run workflows on speccifc tagged nodes
nodeSelector: {}
# nodeSelector:
#   node_pool: default

#  This is used to apply additional labels on k8s resources if needed 
#  and properly tag the team and environment

additionalLabels: {}

tolerations: []
# tolerations:
#   - effect: NoExecute
#     key: workload
#     operator: Equal
#     value: reserved-node

# Seting disruption budget on workflow spec
# If the task is critical to avoid accidental eviction set this to a high number
podDisruptionBudget:
  minAvailable: ""

# Setting up Time to live Strategy, if user don't specify any by default will be 2592000 secs or 30 days max
ttlStrategy:
  secondsAfterCompletion: 2592000 # Time to live after workflow is completed, replaces ttlSecondsAfterFinished
  secondsAfterSuccess: 2592000     # Time to live after workflow is successful
  secondsAfterFailure: 2592000     # Time to live after workflow fails
