{{- if or .Values.serviceAccount.create .Values.serviceAccount.addRBAC -}}
{{- if or (ne .Values.serviceAccount.name "workflows") (.Values.serviceAccount.existingNameSA) -}}
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: {{ include "common.serviceAccountName" . }}-workflows
rbacBindings:
  - name: {{ include "common.serviceAccountName" . }}-workflows
    subjects:
      - kind: ServiceAccount
        name: {{ include "common.serviceAccountName" . }}
    roleBindings:
      - clusterRole: workflows-server
        namespace: {{ .Release.Namespace }}
      - clusterRole: workflows-admin
        namespace: {{ .Release.Namespace }}
      - role: {{ include "common.serviceAccountName" . }}-workflows
        namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
