{{- if .Values.cloudArmor.enabled -}}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  {{- if $.Values.canary.enabled }}
  namespace: {{ .Values.canary.gatewayNamespace }}
  {{- end }}
  name: {{ include "common.name" . }}
spec:
  {{- toYaml .Values.cloudArmor.backendConfig | nindent 2 }}
{{- end }}
