{{- if and .Values.cloudArmor .Values.cloudArmor.enabled -}}
{{- $ingressStyles := fromJsonArray (include "ingressStyles" .) }}
{{- range $ingressStyles }}
{{- $ingressStyle := . }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  {{- if eq $ingressStyle "csm" }}
  namespace: {{ $.Values.canary.gatewayNamespace }}
  {{- end }}
  name: {{ include "common.name" $ }}
spec:
  secretName: {{ $.Values.cloudArmor.certificate.secretName | default (include "common.cloudArmorTlsSecret" $) }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ $.Values.cloudArmor.certificate.issuer | default "letsencrypt" }}
  commonName: {{ $.Values.cloudArmor.certificate.host | quote }}
  dnsNames:
    - {{ $.Values.cloudArmor.certificate.host | quote }}
{{- if $.Values.cloudArmor.certificate.alternativeDnsNames }}
    {{- toYaml $.Values.cloudArmor.certificate.alternativeDnsNames | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
