{{- if .Values.cloudArmor.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "common.name" . }}
spec:
  secretName: {{ .Values.cloudArmor.secretName | default (include "common.cloudArmorTlsSecret" .) }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.cloudArmor.certificate.issuer }}
  {{ range .Values.cloudArmor.hosts -}}
  commonName: {{ .host | quote }}
  dnsNames:
    - {{ .host | quote }}
  {{- end }}
{{- end }}
