{{- if and .Values.cloudArmor.enabled .Values.cloudArmor.frontendConfig -}}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  {{- if $.Values.canary.enabled }}
  namespace: {{ .Values.canary.gatewatNamespace }}
  {{- end }}
  name: {{ include "common.name" . }}
spec:
  {{- toYaml .Values.cloudArmor.frontendConfig | nindent 2 }}
{{- end }}
