{{/* This file is not used now but keeping it in future case of Private gateway applications */}}
{{- if and .Values.ingress.enabled .Values.canary.enabled -}}
{{- $labels := include "common.labels" . -}}
{{- $svcport := .Values.service.port -}}
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  namespace: {{ $.Values.canary.gatewayNamespace }}
  name: {{ include "common.name" . }}
  labels:
    {{- $labels | nindent 4 }}
  {{- if .annotations }}
  annotations:
    {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  selector:
    istio: gateway-private
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    {{- range .Values.ingress.hosts }}
    - {{ .host | quote }}
    {{- end }}
  {{/*
    {{- if .tls }}
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - {{ .Values.service.name | default (include "common.name" .) }}
    {{- range .Values.ingress.hosts }}
    - {{ .host | quote }}
    {{- end }}
    tls:
      mode: SIMPLE
      credentialName: {{ .tls.secretName | default $hostwithdashestls }}
    {{- end }}
    */}}
{{- end }}
