{{- if and .Values.canary.enabled .Values.canary.reverseProxy.autoscaling.enabled }}
{{- $rpAuto := .Values.canary.reverseProxy.autoscaling -}}
{{- $rootAuto := .Values.autoscaling -}}
{{- $min := coalesce $rpAuto.minReplicas $rootAuto.minReplicas -}}
{{- $max := coalesce $rpAuto.maxReplicas $rootAuto.maxReplicas -}}
{{- $metrics := coalesce $rpAuto.metrics $rootAuto.metrics -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "common.reverseProxyName" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "common.reverseProxyName" . }}
  minReplicas: {{ $min }}
  maxReplicas: {{ $max }}
  {{- with $metrics }}
  metrics:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.hpaBehavior.enabled }}
  behavior:
    {{- toYaml .Values.hpaBehavior.behavior | nindent 4 }}
  {{- end }}
{{- end }}
