{{- if and .Values.canary.enabled .Values.canary.reverseProxy.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "common.reverseProxyName" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "common.reverseProxyName" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- toYaml .Values.autoscaling.metrics | nindent 4 }}
  {{- if .Values.hpaBehavior.enabled }}
  behavior:
    {{- toYaml .Values.hpaBehavior.behavior | nindent 4 }}
  {{- end }}
{{- end }}
