{{- if and .Values.canary.reverseProxy.autoscaling.enabled .Values.canary.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "common.reverseProxyName" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "common.reverseProxyName" . }}
  minReplicas: {{ .Values.canary.reverseProxy.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ .Values.canary.reverseProxy.autoscaling.maxReplicas | default 3 }}
  metrics:
    {{- toYaml .Values.canary.reverseProxy.autoscaling.metrics | nindent 4 }}
  {{- if .Values.canary.reverseProxy.autoscaling.behavior }}
  behavior:
    {{- toYaml .Values.canary.reverseProxy.autoscaling.behavior | nindent 4 }}
  {{- end }}
{{- end }}