{{- if and .Values.autoscaling.enabled .Values.canary.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "common.canaryName" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "common.canaryName" . }}
  {{- if and .Values.canary.autoscaling .Values.canary.autoscaling.minReplicas }}
  minReplicas: {{ .Values.canary.autoscaling.minReplicas }}
  {{- else }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  {{- end }}
  {{- if and .Values.canary.autoscaling .Values.canary.autoscaling.maxReplicas }}
  maxReplicas: {{ .Values.canary.autoscaling.maxReplicas }}
  {{- else }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas}}
  {{- end }}
  metrics:
    {{- toYaml .Values.autoscaling.metrics | nindent 4 }}
  {{- if .Values.hpaBehavior.enabled }}
  behavior:
    {{- toYaml .Values.hpaBehavior.behavior | nindent 4 }}
  {{- end }}
{{- end }}
