{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "common.name" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "common.name" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- toYaml .Values.autoscaling.metrics | nindent 4 }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.autoscaling.scaleDown.stabilizationWindowSeconds }}
      policies:
      - type: {{ .Values.autoscaling.scaleDown.policies.type }}
        value: {{ .Values.autoscaling.scaleDown.policies.value }}
        periodSeconds: {{ .Values.autoscaling.scaleDown.policies.periodSeconds }}
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.autoscaling.scaleUp.stabilizationWindowSeconds }}
      policies:
      - type: {{ .Values.autoscaling.scaleUp.policies.percent.type }}
        value: {{ .Values.autoscaling.scaleUp.policies.percent.value }}
        periodSeconds: {{ .Values.autoscaling.scaleUp.policies.percent.periodSeconds }}
      - type: {{ .Values.autoscaling.scaleUp.policies.pod.type }}
        value: {{ .Values.autoscaling.scaleUp.policies.pod.value }}
        periodSeconds: {{ .Values.autoscaling.scaleUp.policies.pod.periodSeconds }}
      selectPolicy: {{ .Values.autoscaling.scaleUp.selectPolicy }}
{{- end }}
