{{- if .Values.cloudArmor.enabled -}}
{{- $svcport := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common.cloudArmorName" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.cloudArmor.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.cloudArmor.staticIpName | default (include "common.name" .) }}
    networking.gke.io/v1beta1.FrontendConfig: {{ include "common.name" . }}
spec:
  rules:
  {{ range .Values.cloudArmor.hosts -}}
  - http:
      paths:
      {{- range .paths }}
      - backend:
        {{- range $backend, $service := .backend }}
          service:
            name: {{ $service.name }}
            port:
              {{- if $service.port }}
              number: {{ $service.port.number }}
              {{- else }}
              number: {{ default $svcport }}
              {{- end }}
        {{- end }}
        path: {{ .path | default "/*" }}
        pathType: {{ .pathType | default "ImplementationSpecific" }}
      {{- end -}}
  {{- end }}
  tls:
    - secretName: {{ include "common.cloudArmorTlsSecret" . }}
{{- end }}
