{{- if and .Values.cloudArmor .Values.cloudArmor.enabled -}}
{{- $svcport := .Values.service.port -}}
{{/* cloudArmor.hosts takes priority over cloudArmor.paths */}}
{{- if hasKey .Values.cloudArmor "hosts" -}}
{{- $commonname := include "common.name" . -}}
{{- $labels := include "common.labels" . -}}
{{- $secretname := .Values.cloudArmor.certificate.secretName | default (include "common.cloudArmorTlsSecret" .) -}}
{{- range .Values.cloudArmor.hosts }}
{{- $hostwithdashes := printf "%s-ca" .host | replace "." "-" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name | default $hostwithdashes }}
  labels:
    {{- $labels | nindent 4 }}
  annotations:
    {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    kubernetes.io/ingress.global-static-ip-name: {{ .staticIpName }}
    networking.gke.io/v1beta1.FrontendConfig: {{ $commonname }}
spec:
  rules:
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range .paths }}
      - backend:
        {{- range $backend, $service := .backend }}
          service:
            name: {{ $service.name }}
            port:
              {{- if $service.port }}
              number: {{ $service.port.number }}
              {{- else }}
              number: {{ default $svcport }}
              {{- end }}
        {{- end }}
        path: {{ .path | default "/*" }}
        pathType: {{ .pathType | default "ImplementationSpecific" }}
      {{- end }}
  tls:
    - secretName: {{ $secretname }}
{{- end }}
{{/* Backwards Compatibility with cloudArmor.paths */}}
{{- else if hasKey .Values.cloudArmor "paths" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common.cloudArmorName" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    {{- with ..Values.cloudArmor.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.cloudArmor.staticIpName | default (include "common.name" .) }}
    networking.gke.io/v1beta1.FrontendConfig: {{ include "common.name" . }}
spec:
  rules:
  - http:
      paths:
      {{- range .Values.cloudArmor.paths }}
      - backend:
        {{- range $backend, $service := .backend }}
          service:
            name: {{ $service.name }}
            port:
              {{- if $service.port }}
              number: {{ $service.port.number }}
              {{- else }}
              number: {{ default $svcport }}
              {{- end }}
        {{- end }}
        path: {{ .path | default "/*" }}
        pathType: {{ .pathType | default "ImplementationSpecific" }}
      {{- end }}
  tls:
    - secretName: {{ .Values.cloudArmor.certificate.secretName | default (include "common.cloudArmorTlsSecret" .) }}
{{- end }}
{{- end }}
