{{- if .Values.cloudArmor.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.cloudArmorName" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.cloudArmor.backendConfig.iap }}
    cloud.google.com/backend-config: '{"ports": {"80":"{{ include "common.name" . }}", "443":"{{ include "common.name" . }}"},"default": "{{ include "common.name" . }}", "customRequestHeaders": {{ .Values.cloudArmor.backendConfig.customHeaders | toJson }}}'
    {{- else }}
    cloud.google.com/backend-config: '{"ports": {"80":"{{ include "common.name" . }}", "443":"{{ include "common.name" . }}"}, "customRequestHeaders": {{ .Values.cloudArmor.backendConfig.customHeaders | toJson }}}'
    {{- end }}
    {{- end }}
spec:
  type: {{ .Values.cloudArmor.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deploymentContainer.port }}
      protocol: TCP
      name: http
  selector:
  {{- if not .Values.podSelectorLabelsOverride }}
    {{- include "common.selectorLabels" . | nindent 4 }}
  {{- end }}
  {{- if .Values.podSelectorLabelsOverride }}
    {{- .Values.podSelectorLabelsOverride | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
