{{- if and .Values.service.enabled .Values.canary.enabled .Values.canary.stableService -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.canary.stableService }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deploymentContainer.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
{{- end }}
