{{- if and .Values.cloudArmor .Values.cloudArmor.enabled -}}
{{- $ingressStyles := fromJsonArray (include "ingressStyles" .) }}
{{- $commonname := include "common.name" . -}}
{{- $labels := include "common.labels" . -}}
{{- $svcport := .Values.service.port -}}
{{- $svclist := list }}

{{/* cloudArmor.hosts takes priority over cloudArmor.paths */}}
{{- if hasKey .Values.cloudArmor "hosts" -}}
  {{- range .Values.cloudArmor.hosts -}}
    {{- range .paths -}}
      {{- $svclist = append $svclist .backend.service }}
    {{- end -}}
  {{- end -}}
{{/* Backwards compatibility with cloudArmor.paths */}}
{{- else if hasKey .Values.cloudArmor "paths" -}}
  {{- range .Values.cloudArmor.paths -}}
    {{- $svclist = append $svclist .backend.service }}
  {{- end -}}
{{- end -}}

{{- $finallist := $svclist | uniq -}}

{{- range $ingressStyles }}
  {{- $ingressStyle := . }}
  {{- range $svc := $finallist }}
---
apiVersion: v1
kind: Service
metadata:
  {{- if eq $ingressStyle "csm" }}
  namespace: {{ $.Values.canary.gatewayNamespace }}
  {{- end }}
  {{- if hasSuffix "-ca" $svc.name }}
  name: {{ $svc.name }}
  {{- else }}
  {{- printf "The Service name '%s' does not meet the Cloud Armor naming standards!" $svc.name | fail }}
  {{- end }}
  labels:
    {{- $labels | nindent 4 }}
  annotations:
    cloud.google.com/backend-config: >
      {{- if $.Values.cloudArmor.backendConfig.iap }}
      {"ports": {"80":"{{ $commonname }}", "443":"{{ $commonname }}"},"default": "{{ $commonname }}"}
      {{- else }}
      {"ports": {"80":"{{ $commonname }}", "443":"{{ $commonname }}"}}
      {{- end }}
spec:
  {{- if and $.Values.cloudArmor.service $.Values.cloudArmor.service.type }}
  type: {{ $.Values.cloudArmor.service.type }}
  {{- else }}
  type: NodePort
  {{- end }}
  ports:
    - port: {{ $svc.port.number }}
      targetPort: {{ if eq $ingressStyle "csm" }}80{{- else }}{{ $svc.targetPort | default $.Values.deploymentContainer.port }}{{- end }}
      protocol: TCP
      name: http
  selector:
    {{- if $.Values.podSelectorLabelsOverride }}
    {{- $.Values.podSelectorLabelsOverride | toYaml | nindent 4 }}
    {{- else if eq $ingressStyle "csm" }}
    istio: gateway-public
    {{- else }}
    app.kubernetes.io/name: {{ trimSuffix "-ca" $svc.name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}