{{- if .Values.cloudArmor.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.cloudArmorName" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80":"{{ include "common.name" . }}", "443":"{{ include "common.name" . }}"}}'
spec:
  type: {{ .Values.cloudArmor.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deploymentContainer.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
{{- end }}
