{{- if .Values.cloudArmor.enabled -}}
{{- $commonname := include "common.name" . -}}
{{- $cselectorlabels := include "common.selectorLabels" . -}}
{{- $labels := include "common.labels" . -}}
{{- range .Values.cloudArmor.paths }}

---
apiVersion: v1
kind: Service
metadata:
  {{- if hasSuffix "-ca" .backend.service.name  }}
  name: {{ .backend.service.name }}
  {{- else }}
  {{- printf "The Service name '%s' does not meet the Cloud Armor naming standards!" .backend.service.name | fail }}
  {{- end }}
  labels:
    {{ $labels | nindent 4 }}
  annotations:
    {{- if $.Values.cloudArmor.backendConfig.iap }}
    cloud.google.com/backend-config: '{"ports": {"80":"{{ $commonname }}", "443":"{{ $commonname }}"},"default": "{{ $commonname }}"}'
    {{- else }}
    cloud.google.com/backend-config: '{"ports": {"80":"{{ $commonname}}", "443":"{{ $commonname }}"}}'
    {{- end }}
spec:
  type: {{ $.Values.cloudArmor.service.type }}
  ports:
    - port: {{ .backend.service.port.number }}
      targetPort: {{ $.Values.deploymentContainer.port }}
      protocol: TCP
      name: http
  selector:
  {{- if not $.Values.podSelectorLabelsOverride }}
    app.kubernetes.io/name: {{ trimSuffix "-ca" .backend.service.name}}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  {{- end }}
  {{- if $.Values.podSelectorLabelsOverride }}
    {{- $.Values.podSelectorLabelsOverride | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
