{{- if .Values.cloudArmor.enabled -}}
{{- $commonname := include "common.name" . -}}
{{- $labels := include "common.labels" . -}}
{{- $svclist := list }}
{{- range $k, $v := .Values.cloudArmor.paths -}}
{{ $svclist = append $svclist $v.backend.service }}
{{ end }}
{{- $finallist :=  $svclist | uniq | toYaml -}}
#{{- $finallist :=  $svclist | uniq  -}}
{{- range $k, $v := $finallist }}

---
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.canary.enabled -}}
  namespace: sys
  {{- end }}
  {{- if hasSuffix "-ca" .backend.service.name  }}
  name: {{ .backend.service.name }}
  {{- else }}
  {{- printf "The Service name '%s' does not meet the Cloud Armor naming standards!" $v.name | fail }}
  {{- end }}
  labels:
    {{- $labels | nindent 4 }}
  annotations:
    {{- if $.Values.cloudArmor.backendConfig.iap }}
    cloud.google.com/backend-config: '{"ports": {"80":"{{ $commonname }}", "443":"{{ $commonname }}"},"default": "{{ $commonname }}"}'
    {{- else }}
    cloud.google.com/backend-config: '{"ports": {"80":"{{ $commonname}}", "443":"{{ $commonname }}"}}'
    {{- end }}
spec:
  type: {{ $.Values.cloudArmor.service.type }}
  ports:
    - port: {{ $v.port.number }}
      targetPort: {{ $v.targetPort | default $.Values.deploymentContainer.port }}
      protocol: TCP
      name: http
  selector:
  {{- if $.Values.podSelectorLabelsOverride }}
    {{- $.Values.podSelectorLabelsOverride | toYaml | nindent 4 }}
  {{- else if $.Values.canary.enabled }}
    app.kubernetes.io/name=csm-edgeproxy-public
  {{- else }}
    app.kubernetes.io/name: {{ trimSuffix "-ca" $v.name}}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  {{- end }}
{{- end }}
{{- end }}
