{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (include "common.name" .) }}
  annotations:
    {{- if .Values.service.annotations }}
    {{- toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    {{- if .Values.additionalLabels }}
      {{- .Values.additionalLabels | toYaml | nindent 6 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deploymentContainer.port }}
      protocol: TCP
      name: http
  selector:
  {{- if not .Values.podSelectorLabelsOverride }}
    {{- include "common.selectorLabels" . | nindent 4 }}
  {{- end }}
  {{- if .Values.podSelectorLabelsOverride }}
    {{- .Values.podSelectorLabelsOverride | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
