{{- if .Values.canary.enabled -}}
{{- $canaryWeight := .Values.canary.weight | default 5 }}
{{- $effectiveCanaryWeight := min (max $canaryWeight 0) 100 }}
{{- $remainingWeight := sub 100 $effectiveCanaryWeight }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.service.name | default (include "common.name" .) }}
spec:
  gateways:
  - mesh
  {{- if .Values.ingress.enabled }}
  - sys/{{ .Values.service.name | default (include "common.name" .) }}
  {{- end }}
  hosts:
  - {{ .Values.service.name | default (include "common.name" .) }}
  {{- range .Values.ingress.hosts }}
  - {{ .host | quote }}
  {{- end }}
  http:
  - route:
    - destination:
        host: {{ .Values.service.name | default (include "common.name" .) }}
        subset: canary
      weight: {{ $effectiveCanaryWeight }}
    - destination:
        host: {{ .Values.service.name | default (include "common.name" .) }}
        subset: production
      weight: {{ $remainingWeight }}
{{- end }}
