{{- if .Values.customScriptRunner.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ include "common.name" . }}-runner
  generateName: {{ include "common.name" . }}-runner-
spec:
  arguments:
    parameters:
    - name: image
      value: "{{ .Values.customScriptRunner.image.repository | default .Values.image.repository }}"
    - name: tag
      value: "{{ .Values.customScriptRunner.image.tag }}"
    - name: args
      value: "{{ .Values.customScriptRunner.args }}"
  entrypoint: main-runner
  serviceAccountName: workflows
  templates:
  
  - name: main-runner
    steps:
    - - name: log-parameters
        template: log-parameters
    - - name: script-runner
        template: runner
        arguments:
          parameters:
          - name: args
            value: "{{`{{workflow.parameters.args}}`}}"

  - name: log-parameters
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo 'Image:{{`{{workflow.parameters.image}}`}} Tag:{{`{{workflow.parameters.tag}}`}} Args:{{`{{workflow.parameters.args}}`}}'"]

  - name: runner
    inputs:
      parameters:
      - name: args
    container:
      image: "{{`{{workflow.parameters.image}}`}}:{{`{{workflow.parameters.tag}}`}}"
      command: [sh, -c]
      args: ["{{`{{ inputs.parameters.args }}`}}"]
      envFrom:
      {{- if .Values.existingConfigMapName }}
      - configMapRef:
          name: {{ .Values.existingConfigMapName }}
      {{- end }}
      {{- if .Values.env }}
      - configMapRef:
          name: {{ .Values.configMapName | default (include "common.name" .) }}
      {{- end}}
      {{- if and (.Values.createSecret) (not .Values.createSecretName) }}
      - secretRef:
          name: {{ include "common.name" . }}
      {{- else if and (.Values.createSecret) (.Values.createSecretName) }}
      - secretRef:
          name: {{ .Values.createSecretName }}
      {{- else if and (.Values.existingSecretName) (not .Values.createSecret) }}
      - secretRef:
          name: {{ .Values.existingSecretName }}
      {{- else }}
      {{- end }}
      env:
      - name: NODE_ENV
        value: {{ .Values.environment }}
      resources:
        {{- toYaml .Values.customScriptRunner.resources | nindent 12 }}
{{- end }}
