{{- range $namespace, $spec := .Values.devNamespaces }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $namespace }}
  labels:
    {{- include "tekton-common.labels" $ | nindent 4 }}
---
{{- end }}
