apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: tekton-secret-store
spec:
  provider:
    gcpsm:
      projectID: dpe-internal-6622
      auth:
        workloadIdentity:
          clusterLocation: us-central1
          clusterName: general-1
          clusterProjectID: internal-1-4825
          serviceAccountRef:
            name: tekton-secrets
            namespace: {{ .Release.Namespace }}
