{{- $namespaces := concat ( list .Release.Namespace ) ( keys .Values.devNamespaces ) -}}
{{- range $namespaces }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-secrets
  namespace: {{ . }}
spec:
  refreshInterval: 2h
  secretStoreRef:
    kind: ClusterSecretStore
    name: tekton-secret-store
  target:
    name: tekton-gh-secrets
    creationPolicy: Owner
  data:
    - secretKey: id_rsa
      remoteRef:
        key: github_sa_id_ed25519
    - secretKey: known_hosts
      remoteRef:
        key: github_known_keys
    - secretKey: config
      remoteRef:
        key: config
    - secretKey: github_pkg_pat
      remoteRef:
        key: github_sa_tekton_pat
    - secretKey: github_feedback_pat
      remoteRef:
        key: github_feedback_pat
    - secretKey: secretToken
      remoteRef:
        {{- if eq . $.Release.Namespace }}
        key: gh-general-wh-secret
        {{- else }}
        key: {{ printf "gh-general-wh-secret-%s" . }}
        {{- end }}
---
{{- end -}}
