apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secrets-slack
spec:
  refreshInterval: 2h
  secretStoreRef:
    kind: ClusterSecretStore
    name: tekton-secret-store
  target:
    name: slack-secrets
    creationPolicy: Owner
  data:
    - secretKey: SLACK_BOT_TOKEN
      remoteRef:
        key: slack_bot_sre_webhook
