apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.secrets.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ required "Service account name for secrets is required!" .Values.secrets.serviceAccount.name }}
secrets:
  - name: tekton-gen-secrets
