$schema: "http://json-schema.org/draft-07/schema#"
type: object
properties:
  common:
    type: object
    properties:
      enabled:
        type: boolean
        default: true
      namespace:
        type: string

    # Validate required fields only if enabled is true
    if:
      properties:
        enabled:
          const: true
    then:
      required:
        - namespace
