{{- if .Values.policySets.common.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  labels:
    {{- include "kyverno-policies.labels" . | nindent 4 }}
  annotations:
    policies.kyverno.io/title: Require Limits and Requests
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Deployment, DaemonSet, Statefulset, Job, Cronjob
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      As application workloads share cluster resources, it is important to limit resources
      requested and consumed by each Pod. It is recommended to require resource requests and
      limits per Pod, especially for memory and CPU. If a Namespace level request or limit is specified,
      This policy validates that all containers have something specified for memory and CPU
      requests and memory limits.
  name: common-resources
spec:
  validationFailureAction: {{ .Values.policySets.common.validationFailureAction }}
  rules:
    - name: resources-set
      match:
        any:
        - resources:
            kinds:
            - Deployment
            - DaemonSet
            - StatefulSet
            - Job
      validate:
        message: "CPU and memory resource requests and limits are required"
        pattern:
          spec:
            template:
              spec:
                containers:
                  - name: "*"
                    resources:
                      {{- if .Values.policySets.common.enforceLimits }}
                      limits:
                        memory: "?*"
                        cpu: "?*"
                      {{- end }}
                      requests:
                        memory: "?*"
                        cpu: "?*"
    - name: cronjob-resources
      match:
        any:
          - resources:
              kinds:
              - CronJob
      validate:
        message: "CPU and memory resource requests and limits are required"
        pattern:
          spec:
            jobTemplate:
              spec:
                template:
                  spec:
                    containers:
                      - name: "*"
                        resources:
                          {{- if .Values.policySets.common.enforceLimits }}
                          limits:
                            memory: "?*"
                            cpu: "?*"
                          {{- end }}
                          requests:
                            memory: "?*"
                            cpu: "?*"
{{- end }}
