{{- if .Values.policySets.common.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: ingress
  namespace: {{ .Values.policySets.common.namespace }}
  labels:
    {{- include "kyverno-policies.labels" . | nindent 4 }}
  annotations:
    policies.kyverno.io/title: Require Requests and Limits
    policies.kyverno.io/category: Security Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Ingress
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      This policy alerts on ingress configurations within the cluster that are not private. Public exposure
      of applications without proper security measures poses significant risks. It is recommended
      to use Cloud Armor instead of public nginx for enhanced protection,
      customizable security rules, and improved control over incoming traffic.
spec:
  validationFailureAction: {{ .Values.policySets.common.validationFailureAction }}
  rules:
    - name: public-ingress
      match:
        any:
        - resources:
            kinds:
            - Ingress
      exclude:
        any:
        - resources:
            namespaces:
            - sys
        - resources:
            kinds:
            - Ingress
            selector:
              matchLabels:
                kyverno-ingress-policy: skip
      validate:
        message: "Public ingress detected. Remove Public Ingress and switch to Cloud Armor."
        pattern:
          metadata:
            annotations:
              =(kubernetes.io/ingress.class): "!nginx-public"
{{- end }}
