{{- if .Values.policySets.common.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: resources
  namespace: {{ .Values.policySets.common.namespace }}
  labels:
    {{- include "kyverno-policies.labels" . | nindent 4 }}
  annotations:
    policies.kyverno.io/title: Require Requests and Limits
    policies.kyverno.io/category: {{ .Values.policySets.common.resources.category }}
    policies.kyverno.io/severity: {{ .Values.policySets.common.resources.severity }}
    policies.kyverno.io/subject: Deployment, DaemonSet, StatefulSet, CronJob
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      As application workloads share cluster resources, it is important to define resources
      requested and consumed by each Pod. It is recommended to require resource CPU/MEM requests and
      MEM limits per Pod. This policy validates that all containers have something specified for CPU/MEM
      requests and MEM limits.
spec:
  validationFailureAction: {{ .Values.policySets.common.resources.validationFailureAction }}
  rules:
    - name: cpu-mem-requests
      match:
        any:
        - resources:
            kinds:
            - Deployment
            - DaemonSet
            - StatefulSet
      exclude:
        {{ .Values.policySets.common.resources.exclude | toYaml | nindent 8 }}
      validate:
        message: "CPU and Memory resources.requests is required."
        pattern:
          spec:
            template:
              spec:
                containers:
                  - name: "*"
                    resources:
                      requests:
                        memory: "?*"
                        cpu: "?*"
    - name: mem-limits
      match:
        any:
        - resources:
            kinds:
            - Deployment
            - DaemonSet
            - StatefulSet
      exclude:
        {{ .Values.policySets.common.resources.exclude | toYaml | nindent 8 }}
      validate:
        message: "Memory resources.limits is required."
        pattern:
          spec:
            template:
              spec:
                containers:
                  - name: "*"
                    resources:
                      {{- if .Values.policySets.common.checkLimits }}
                      limits:
                        memory: "?*"
                      {{- end }}
    - name: cron-cpu-mem-requests
      match:
        any:
        - resources:
            kinds:
            - CronJob
      exclude:
        {{ .Values.policySets.common.resources.exclude | toYaml | nindent 8 }}
      validate:
        message: "CPU and Memory resource.requests is required."
        pattern:
          spec:
            jobTemplate:
              spec:
                template:
                  spec:
                    containers:
                      - name: "*"
                        resources:
                          requests:
                            memory: "?*"
                            cpu: "?*"
    - name: cron-mem-limits
      match:
        any:
          - resources:
              kinds:
              - CronJob
      exclude:
        {{ .Values.policySets.common.resources.exclude | toYaml | nindent 8 }}
      validate:
        message: "Memory resource.limits is required."
        pattern:
          spec:
            jobTemplate:
              spec:
                template:
                  spec:
                    containers:
                      - name: "*"
                        resources:
                          {{- if .Values.policySets.common.checkLimits }}
                          limits:
                            memory: "?*"
                          {{- end }}
{{- end }}
