{{- if .Values.policySets.common.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: labels
  namespace: {{ .Values.policySets.common.namespace }}
  annotations:
    policies.kyverno.io/title: Label `team` is required
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Deployment
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      Replica count for a Deployment must be greater than or equal to 2.
spec:
  validationFailureAction: {{ .Values.policySets.common.validationFailureAction }}
  rules:
    - name: label-team-required
      match:
        any:
        - resources:
            kinds:
            - Deployment
      validate:
        message: "The label `team` is required."
        pattern:
          spec:
            template:
              metadata:
                labels:
                  team: "?*"
{{- end }}
