{{- if .Values.policySets.common.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: app-labels
  namespace: {{ .Values.policySets.common.namespace }}
  annotations:
    policies.kyverno.io/title: Label `application` is required
    policies.kyverno.io/category: {{ .Values.policySets.common.labels.category }}
    policies.kyverno.io/severity: {{ .Values.policySets.common.labels.severity }}
    policies.kyverno.io/subject: Deployment, CronJob
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      This policy ensures that Deployments have a required label `application` defined. 
      Assigning a `application` label to Deployments is a best practice for organizational clarity and resource management. 
      It helps in categorizing and identifying resources belonging to specific teams or departments within a Kubernetes cluster.
spec:
  validationFailureAction: {{ .Values.policySets.common.app-labels.validationFailureAction }}
  rules:
    - name: label-application-required
      match:
        any:
        - resources:
            kinds:
            - Deployment
      exclude:
        {{ .Values.policySets.common.app-labels.exclude | toYaml | nindent 8 }}
      validate:
        message: "Label `application` is required."
        anyPattern:
        - metadata:
            labels:
              application: "?*"
        - spec:
            template:
              metadata:
                labels:
                  application: "?*"
    - name: cron-label-application-required
      match:
        any:
          - resources:
              kinds:
              - CronJob
      exclude:
        {{ .Values.policySets.common.app-labels.exclude | toYaml | nindent 8 }}
      validate:
        message: "Label `application` is required."
        anyPattern:
        - metadata:
            labels:
              application: "?*"
        - spec:
            template:
              metadata:
                labels:
                  application: "?*"
{{- end }}
