{{- if .Values.policySets.common.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: probes-test003
  namespace: {{ .Values.policySets.common.namespace }}
  annotations:
    policies.kyverno.io/title: Require Probes
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Deployment
    policies.kyverno.io/description: >-
      Liveness and readiness probes need to be configured to correctly manage a Pod's
      lifecycle during deployments, restarts, and upgrades. For each Pod, a periodic
      `livenessProbe` is performed by the kubelet to determine if the Pod's containers
      are running or need to be restarted. A `readinessProbe` is used by Services
      and Deployments to determine if the Pod is ready to receive network traffic.
      A `startupProbe` is used to determine if a container is ready to accept traffic
      before the container is added to the service's endpoints.
spec:
  validationFailureAction: {{ .Values.policySets.common.validationFailureAction }}
  background: true
  rules:
  - name: livenessprobe-required
    match:
      any:
      - resources:
          kinds:
          - Deployment
    exclude:
      any:
      - resources:
          namespaces:
          - policy
          - sys
          - workflows
      - resources:
          kinds:
          - Deployment
          selector:
            matchLabels:
              kyverno: skip-probes-policy
    preconditions:
      all:
      - key: "{{`{{request.operation || 'BACKGROUND'}}`}}"
        operator: AnyIn
        value:
        - CREATE
        - UPDATE
    validate:
      message: "`livenessProbe` is required for all containers."
      foreach:
      - list: request.object.spec.template.spec.containers[]
        deny:
          conditions:
            all:
            - key: livenessProbe
              operator: AllNotIn
              value: "{{`{{ element.keys(@)[] }}`}}"
  - name: readinessprobe-required
    match:
      any:
      - resources:
          kinds:
          - Deployment
    exclude:
      any:
      - resources:
          namespaces:
          - policy
          - sys
          - workflows
    preconditions:
      all:
      - key: "{{`{{request.operation || 'BACKGROUND'}}`}}"
        operator: AnyIn
        value:
        - CREATE
        - UPDATE
    validate:
      message: "`readinessProbe` is required for all containers."
      foreach:
      - list: request.object.spec.template.spec.containers[]
        deny:
          conditions:
            all:
            - key: readinessProbe
              operator: AllNotIn
              value: "{{`{{ element.keys(@)[] }}`}}"
  - name: startupprobe-required
    match:
      any:
      - resources:
          kinds:
          - Deployment
    exclude:
      any:
      - resources:
          namespaces:
          - policy
          - sys
          - workflows
    preconditions:
      all:
      - key: "{{`{{request.operation || 'BACKGROUND'}}`}}"
        operator: AnyIn
        value:
        - CREATE
        - UPDATE
    validate:
      message: "`startupProbe` is required for all containers."
      foreach:
      - list: request.object.spec.template.spec.containers[]
        deny:
          conditions:
            all:
            - key: startupProbe
              operator: AllNotIn
              value: "{{`{{ element.keys(@)[] }}`}}"
{{- end }}
