{{- if .Values.policySets.common.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: labels
  namespace: {{ .Values.policySets.common.namespace }}
  annotations:
    policies.kyverno.io/title: Label `team` is required
    policies.kyverno.io/category: {{ .Values.policySets.common.labels.category }}
    policies.kyverno.io/severity: {{ .Values.policySets.common.labels.severity }}
    policies.kyverno.io/subject: Deployment, Cronjob
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      This policy ensures that Deployments have a required label `team` defined. 
      Assigning a `team` label to Deployments is a best practice for organizational clarity and resource management. 
      It helps in categorizing and identifying resources belonging to specific teams or departments within a Kubernetes cluster.
spec:
  validationFailureAction: {{ .Values.policySets.common.labels.validationFailureAction }}
  rules:
    - name: label-team-required
      match:
        any:
        - resources:
            kinds:
            - Deployment
      exclude:
        {{ .Values.policySets.common.labels.exclude | toYaml | nindent 8 }}
      validate:
        message: "Label `team` is required."
        pattern:
          spec:
            template:
              metadata:
                labels:
                  team: "?*"
    - name: cron-label-team-required
      match:
        any:
          - resources:
              kinds:
              - CronJob
      exclude:
        {{ .Values.policySets.common.labels.exclude | toYaml | nindent 8 }}
      validate:
        message: "Label `team` is required."
        pattern:
          metadata:
            labels:
              team: "?*"
{{- end }}
