{{- if .Values.policySets.common.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: security-context
  namespace: {{ .Values.policySets.common.namespace }}
  annotations:
    policies.kyverno.io/title: Require Run As Non-Root User
    policies.kyverno.io/category: {{ .Values.policySets.common.securityContext.category }}
    policies.kyverno.io/severity: {{ .Values.policySets.common.securityContext.severity }}
    policies.kyverno.io/subject: Deployment, Cronjob
    kyverno.io/kyverno-version: 1.6.0
    kyverno.io/kubernetes-version: "1.22-1.23"
    policies.kyverno.io/description: >-
      Containers must be required to run as non-root users. This policy ensures
      `runAsUser` is either unset or set to a number greater than zero.      
spec:
  validationFailureAction: {{ .Values.policySets.common.securityContext.validationFailureAction | default .Values.policySets.common.validationFailureAction }}
  background: true
  rules:
    - name: run-as-user-non-root
      match:
        any:
        - resources:
            kinds:
            - Deployment
      exclude:
        {{ .Values.policySets.common.securityContext.exclude | toYaml | nindent 8 }}
      validate:
        message: >-
          Running as root is not allowed. The fields spec.securityContext.runAsUser,
          spec.containers[*].securityContext.runAsUser must be unset or
          set to a number greater than zero.          
        pattern:
          spec:
            template:
              spec:
                =(securityContext):
                  =(runAsUser): ">0"
                containers:
                - =(securityContext):
                    =(runAsUser): ">0"
    - name: cron-run-as-user-non-root
      match:
        any:
        - resources:
            kinds:
            - CronJob
      exclude:
        {{ .Values.policySets.common.securityContext.exclude | toYaml | nindent 8 }}
      validate:
        message: >-
          Running as root is not allowed. The fields spec.securityContext.runAsUser,
          spec.containers[*].securityContext.runAsUser must be unset or
          set to a number greater than zero.
        pattern:
          spec:
            jobTemplate:
              spec:
                template:
                  spec:
                    =(securityContext):
                      =(runAsUser): ">0"
                    containers:
                    - =(securityContext):
                        =(runAsUser): ">0"
{{- end }}
