apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "csm-edgeproxy.name" . }}
  labels:
    {{- include "csm-edgeproxy.labels" . | nindent 4 }}
spec:
{{- if and (not .Values.podDisruptionBudget.minAvailable) (not .Values.podDisruptionBudget.maxUnavailable) }}
  maxUnavailable: 1
{{- end}}
{{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
{{- end }}
{{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
{{- end }}
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: {{ .Values.gatewayClass }}
