{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "csm-edgeproxy.name" . }}
  labels:
    {{- include "csm-edgeproxy.labels" . | nindent 4 }}
  annotations:
    {{ with .Values.service.annotations }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: istio-ingressgateway
    istio: {{ .Values.gatewayClass }}
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  - port: 443
    protocol: TCP
    targetPort: 443
{{- end }}
