{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "csm-edgeproxy.serviceAccountName" . }}
  labels:
    {{- include "csm-edgeproxy.labels" . | nindent 4 }}
  annotations:
    {{ with .Values.serviceAccount.annotations }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
