# Default values for common.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

gatewayClass: "istio-ingressgateway"
replicaCount: 2
commonLabels: {}
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.

resources:
  limits:
    memory: 1024Mi
  requests:
    cpu: 1000m
    memory: 1024Mi

service:
  create: true
  annotations: {}
  type: LoadBalancer

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1
  type: RollingUpdate

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  metrics: []

hpaBehavior:
  enabled: false
  behavior: {}
#   scaleDown:
#     stabilizationWindowSeconds: 300
#     policies:
#     - type: Percent
#       value: 100
#       periodSeconds: 15
#   scaleUp:
#     stabilizationWindowSeconds: 0
#     policies:
#     - type: Percent
#       value: 100
#       periodSeconds: 15
#     - type: Pods
#       value: 4
#       periodSeconds: 15
#     selectPolicy: Max

# Type Resource
#
#  metrics:
#  - type: Resource
#    resource:
#      name: cpu
#      target:
#        type: Utilization
#        averageUtilization: 50
#  - type: Resource
#    resource:
#      name: memory
#      target:
#        type: AverageValue
#        averageValue: 100Mi
#
# Type External
#
#  metrics:
#  - type: External
#    external:
#      metric:
#        name: pubsub.googleapis.com|subscription|num_undelivered_messages
#        selector:
#          matchLabels:
#            resource.labels.subscription_id: payment-method-update
#      target:
#        type: AverageValue
#        averageValue: 100

# PodDisruptionBudget
#
# minAvailable and maxUnavailable are mutually exclusive, only one should be set.
#
# If podDisruptionBudget is enabled but no minAvailable or maxUnavailable fields
# are set, the PodDisruptionTemplate template will default to `minAvailable: 15%`.
#
# The value for minAvailable and maxUnavailable should either be set to an integer
# or a percentage.  For more information see the official documentation:
#
# https://kubernetes.io/docs/tasks/run-application/configure-pdb/
podDisruptionBudget: {}
  # minAvailable: "75%"
  # maxUnavailable: 1 # default
