$schema: "http://json-schema.org/draft-07/schema#"
type: object
definitions: {}
properties:
  gateways:
    type: object
  routes:
    type: object
    properties:
      enabled:
        type: boolean
      default:
        $ref: "#/$defs/routeDefault"
      items:
        type: array
        minItems: 0
        items:
          $ref: "#/$defs/route"
    additionalProperties: false
  healthCheckPolicies:
    type: object
    properties:
      enabled:
        type: boolean
      default:
        $ref: "#/$defs/healthCheckPolicyDefault"
      items:
        type: array
        minItems: 0
        items:
          $ref: "#/$defs/healthCheckPolicy"
    additionalProperties: false
required:
  - routes
  - healthCheckPolicies

$defs:
  healthCheckPolicy:
    type: object
    properties:
      name:
        type: string
      enabled:
        type: boolean
      rawSpec:
        type: boolean
      spec:
        type: object
        properties:
          default:
            type: object
            properties:
              checkIntervalSec:
                type: integer
                minimum: 1
              timeoutSec:
                type: integer
                minimum: 1
              healthyThreshold:
                type: integer
                minimum: 1
              unhealthyThreshold:
                type: integer
                minimum: 1
              logConfig:
                type: object
                properties:
                  enabled:
                    type: boolean
                required:
                  - enabled
                additionalProperties: false
              config:
                type: object
                properties:
                  type:
                    type: string
                    enum:
                      - HTTP
                      - GRPC
                  httpHealthCheck:
                    type: object
                    properties:
                      port:
                        type: integer
                        minimum: 1
                        maximum: 65535
                      requestPath:
                        type: string
                    required:
                      - port
                      - requestPath
                    additionalProperties: false
                  grpcHealthCheck:
                    type: object
                    properties:
                      port:
                        type: integer
                        minimum: 1
                        maximum: 65535
                    required:
                      - port
                    additionalProperties: false
                additionalProperties: false
            additionalProperties: false
          targetRef:
            type: object
            properties:
              group:
                type: string
                const: ""
              kind:
                type: string
                const: Service
              name:
                type: string
            required:
              - name
            additionalProperties: false
        additionalProperties: false
        required:
          - default
          - targetRef
    required:
      - name
      - spec
    if:
      required:
        - rawSpec
      properties:
        rawSpec:
          const: true
    then:
      properties:
        spec:
          properties:
            targetRef:
              required:
                - group
                - kind
                - name
            default:
              properties:
                config:
                  required:
                    - type
                  anyOf:
                    - required:
                        - httpHealthCheck
                    - required:
                        - grpcHealthCheck
    else:
      properties:
        spec:
          properties:
            default:
              required:
                - config
              properties:
                config:
                  required:
                    - httpHealthCheck
    additionalProperties: false
  route:
    type: object
    properties:
      name:
        type: string
      enabled:
        type: boolean
      kind:
        type: string
        enum:
          - HTTPRoute
          - GRPCRoute
      rawSpec:
        type: boolean
      spec:
        type: object
        properties:
          hostnames:
            type: array
            minItems: 1
            items:
              type: string
              pattern: "^([a-zA-Z0-9]+(-[a-zA-Z0-9]+)*\\.)*(trydave\\.com|daveapi\\.com|daveapi\\.io)$"
          parentRefs:
            type: array
            # Only a single parent ref is supported for the time being
            minItems: 1
            maxItems: 1
            items:
              type: object
              properties:
                group:
                  type: string
                  const: "gateway.networking.k8s.io"
                kind:
                  type: string
                  const: Gateway
                name:
                  type: string
                  maxLength: 63
                  pattern: "^[a-z]([-a-z0-9]*[a-z0-9])?$"
                namespace:
                  type: string
                  const: shared-gateways
              additionalProperties: false
          rules:
            type: array
            minItems: 1
            items:
              type: object
              properties:
                backendRefs:
                  type: array
                  # For the time being, we only support a single backend ref per rule,
                  # so minItems and maxItems are both set to 1
                  minItems: 1
                  maxItems: 1
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      port:
                        type: integer
                        minimum: 1
                        maximum: 65535
                      weight:
                        type: integer
                        # For the time being, we only support a single backend ref per rule,
                        # so weight must be 1
                        const: 1
                      group:
                        type: string
                        const: ""
                      kind:
                        type: string
                        const: Service
                    required:
                      - name
                      - port
                    additionalProperties: false
                matches:
                  type: array
                  minItems: 1
                  items:
                    type: object
                    properties:
                      path:
                        type: object
                        properties:
                          type:
                            type: string
                            enum:
                              - PathPrefix
                              - PathExact
                              - PathRegex
                          value:
                            type: string
                        additionalProperties: false
                    additionalProperties: false
                filters:
                  type: array
                  minItems: 1
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        enum:
                          - RequestRedirect
                      requestRedirect:
                        type: object
                        properties:
                          scheme:
                            type: string
                            enum:
                              - http
                              - https
                          hostname:
                            type: string
                          statusCode:
                            type: integer
                            enum:
                              - 301
                              - 302
                              - 307
                              - 308
                        additionalProperties: false
                    additionalProperties: false
                timeouts:
                  type: object
                  properties:
                    backendRequest:
                      type: string
                      pattern: "^([0-9]{1,5}(h|m|s|ms)){1,4}$"
                    request:
                      type: string
                      pattern: "^([0-9]{1,5}(h|m|s|ms)){1,4}$"
                  anyOf:
                    - required:
                        - backendRequest
                    - required:
                        - request
                  additionalProperties: false
              additionalProperties: false
        required:
          - hostnames
          - rules
        additionalProperties: false
    required:
      - name
      - spec
    if:
      required:
        - rawSpec
      properties:
        rawSpec:
          const: true
    then:
      properties:
        spec:
          required:
            - parentRefs
          properties:
            parentRefs:
              items:
                required:
                  - name
                  - namespace
            rules:
              items:
                properties:
                  backendRefs:
                    items:
                      required:
                        - name
                        - port
                        - weight
                  matches:
                    items:
                      properties:
                        path:
                          required:
                            - type
                            - value
                  filters:
                    items:
                      required:
                        - type
                      if:
                        properties:
                          type:
                            const: RequestRedirect
                      then:
                        required:
                          - requestRedirect
    additionalProperties: false
  routeDefault:
    type: object
    properties:
      spec:
        type: object
        properties:
          parentRef:
            type: object
            properties:
              group:
                type: string
                const: "gateway.networking.k8s.io"
              kind:
                type: string
                const: Gateway
              name:
                type: string
                maxLength: 63
                pattern: "^[a-z]([-a-z0-9]*[a-z0-9])?$"
              namespace:
                type: string
                const: shared-gateways
            additionalProperties: false
          rule:
            type: object
            properties:
              backendRef:
                type: object
                properties:
                  group:
                    type: string
                    const: ""
                  kind:
                    type: string
                    const: Service
                  weight:
                    type: integer
                    const: 1
                additionalProperties: false
              match:
                type: object
                properties:
                  path:
                    type: object
                    properties:
                      type:
                        type: string
                        enum:
                          - PathPrefix
                          - PathExact
                          - PathRegex
                      value:
                        type: string
                    additionalProperties: false
                additionalProperties: false
              filter:
                type: object
                properties:
                  type:
                    type: string
                    enum:
                      - RequestRedirect
                  requestRedirect:
                    type: object
                    properties:
                      scheme:
                        type: string
                        enum:
                          - http
                          - https
                      hostname:
                        type: string
                      statusCode:
                        type: integer
                        enum:
                          - 301
                          - 302
                          - 307
                          - 308
                    additionalProperties: false
                additionalProperties: false
            additionalProperties: false
        additionalProperties: false
    additionalProperties: false
  healthCheckPolicyDefault:
    type: object
    properties:
      spec:
        type: object
        properties:
          default:
            type: object
            properties:
              checkIntervalSec:
                type: integer
                minimum: 1
              timeoutSec:
                type: integer
                minimum: 1
              healthyThreshold:
                type: integer
                minimum: 1
              unhealthyThreshold:
                type: integer
                minimum: 1
              logConfig:
                type: object
                properties:
                  enabled:
                    type: boolean
                additionalProperties: false
              config:
                type: object
                properties:
                  type:
                    type: string
                    enum:
                      - HTTP
                      - GRPC
                additionalProperties: false
            additionalProperties: false
          targetRef:
            type: object
            properties:
              group:
                type: string
                const: ""
              kind:
                type: string
                const: Service
            additionalProperties: false
        additionalProperties: false
    additionalProperties: false
additionalProperties: false
