$schema: "http://json-schema.org/draft-07/schema#"
type: object
properties:
  name:
    type: string
  enabled:
    type: boolean
  additionalLabels:
    type: object
    additionalProperties:
      type: string
  gateways:
    type: object
  routes:
    type: object
    properties:
      enabled:
        type: boolean
      default:
        $ref: "./gatewayapi.schema.yaml#/$defs/routeDefault"
      items:
        type: array
        minItems: 0
        items:
          $ref: "./gatewayapi.schema.yaml#/$defs/route"
    additionalProperties: false
  healthCheckPolicies:
    type: object
    properties:
      enabled:
        type: boolean
      default:
        $ref: "./gatewayapi.schema.yaml#/$defs/healthCheckPolicyDefault"
      items:
        type: array
        minItems: 0
        items:
          $ref: "./gatewayapi.schema.yaml#/$defs/healthCheckPolicy"
    additionalProperties: false
  gcpBackendPolicies:
    type: object
    properties:
      enabled:
        type: boolean
      default:
        $ref: "./gatewayapi.schema.yaml#/$defs/gcpBackendPolicyDefault"
      items:
        type: array
        minItems: 0
        items:
          $ref: "./gatewayapi.schema.yaml#/$defs/gcpBackendPolicy"
    additionalProperties: false
required:
  - routes
  - healthCheckPolicies
  - gcpBackendPolicies
additionalProperties: false
