{{- if .Values.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/hook: Skip
  name: {{ .Values.createSecretName | default (include "job.name" .) }}
  labels:
    {{- include "job.labels" . | nindent 4 }}
data:
{{- end }}
