{{- if .Values.cloudArmor.enabled -}}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "common.name" . }}
spec:
  securityPolicy:
    name: {{ .Values.cloudArmor.securityPolicyName | default (include "common.name" .) | quote }}
{{- end }}
