{{- if .Values.cloudArmor.enabled -}}
apiVersion: cert-manager.io/v1
kind: "Certificate"
metadata:
  name: {{ .Values.service.name | default (include "common.name" .) }}
spec:
  secretName: {{ .Values.cloudArmor.secretName }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.certificate.issuer }}
  commonName: {{ .Values.cloudArmor.host | quote }}
  dnsNames:
    - {{ .Values.cloudArmor.host | quote }}
{{- end }}
