apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-configmap
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  {{- .Values.env | toYaml | nindent 2 }}
