apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.name" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- include "common.podAnnotations" . | nindent 6 }}
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "common.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deploymentContainer.port  }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.deploymentContainer.livenessProbe.path }}
              port: {{ .Values.deploymentContainer.livenessProbe.port }}
          readinessProbe:
            httpGet:
              path:  {{ .Values.deploymentContainer.readinessProbe.path }}
              port:  {{ .Values.deploymentContainer.readinessProbe.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.deploymentContainer.command }}
          command:
            {{- toYaml .Values.deploymentContainer.command | nindent 12 }}
          {{- end }}
          env:
            {{/*
            Environment variables used by the common logger
            https://github.com/dave-inc/logger/blob/6c69fe2cba9bb954494fe9c6b5297633c1a19aeb/README.md#L69
            */}}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_ENV
              value: {{ .Values.environment }}
            - name: DEPLOYMENT_NAME
              value: {{ include "common.name" . }}
           {{- range $name, $value := .Values.env }}
            - name: {{ $name }}
              value: {{ $value | quote }}
           {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "common.name" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
