{{- if .Values.ingress.enabled -}}
{{- $name := include "common.name" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{ if .Values.cloudArmor.enabled -}}
  name: {{ .Values.cloudArmor.name | default (include "common.name" .) }}
  {{- else -}}
  name: {{ $name }}
  {{- end }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- if or .Values.cloudArmor.enabled .Values.ingress.annotations }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{ if .Values.cloudArmor.enabled -}}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.cloudArmor.staticIpName | default (include "common.name" .) }}
    networking.gke.io/v1beta1.FrontendConfig: {{ include "common.name" . }}
    {{- end -}}
  {{- end }}
spec:
  rules:
  {{ if .Values.cloudArmor.enabled -}}
  {{- range .Values.ingress.hosts -}}
  - http:
      paths:
      {{- if gt (.paths | len) 1 -}}
      {{- range .paths }}
      - backend:
        {{- range $backend, $service := .backend }}
          service:
            name: {{ $service.name }}
            port:
              {{- range $port, $number := $service.port }}
              number: {{ $number }}
              {{- end }}
        {{- end }}
        path: {{ .path | default "/*" | quote }}
        pathType: {{ .pathType | default "ImplementationSpecific" | quote }}
      {{- end -}}
      {{- else }}
      {{- range .paths }}
      - backend:
          service:
            name: {{ $name }}
            port:
              number: {{ $svcPort }}
        path: {{ . | quote }}
        pathType: {{ default "ImplementationSpecific" | quote }}
      {{- end -}}
      {{- end -}}
  {{- end }}
  tls:
    - secretName: {{ .Values.cloudArmor.secretName }}
  {{- else -}}
  {{- range .Values.ingress.hosts -}}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- if gt (.paths | len) 1 -}}
      {{- range .paths }}
      - backend:
        {{- range $backend, $service := .backend }}
          service:
            name: {{ $service.name }}
            port:
              {{- range $port, $number := $service.port }}
              number: {{ $number }}
              {{- end }}
        {{- end }}
        path: {{ .path | default "/" | quote }}
        pathType: {{ .pathType | default "ImplementationSpecific" | quote }}
      {{- end -}}
      {{- else }}
      {{- range .paths }}
      - backend:
          service:
            name: {{ $name }}
            port:
              number: {{ $svcPort }}
        path: {{ . | quote }}
        pathType: {{ default "ImplementationSpecific" | quote }}
      {{- end -}}
      {{- end }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end -}}
  {{- end }}
  {{- end -}}
{{- end }}
