{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.namespace }}@{{ .Values.project }}.iam.gserviceaccount.com
    {{ with .Values.serviceAccount.annotations }}
    {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
