{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.serviceAccountName" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.iamName | default (include "common.serviceAccountName" .) }}@{{ required "A valid GCP Project id is required!" .Values.project }}.iam.gserviceaccount.com
    {{ with .Values.serviceAccount.annotations }}
    {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
