{{- range $name, $val := .Values.jobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $name }}-cron
spec:
  schedule: {{ $val.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: trigger
            image: curlimages/curl
            args: ["curl", "-X", "POST", "--data", "{\"job\": \"{{ $name }}\"}", "el-{{ template "tekton-cron-jobs.eventListenerName" .Values }}.$(NAMESPACE).svc.cluster.local:8080"]
            env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          restartPolicy: Never

{{- end }}
