
{{- if .Values.ingress.enabled -}}
{{- $hostwithdashestls := printf "%s-tls" .Values.ingress.host | replace "." "-" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "tekton-cron"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: "nginx-internal"
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: el-tekton-cron
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ $hostwithdashestls }}
{{- end }}
