apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ include "cloudarmor.name" . }}
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- toYaml .Values.frontendConfig | nindent 2 }}
