{{- if (and .Values.enabled .Values.gcpBackendPolicies.enabled) }}
{{- $seen := dict }}
{{- range $gcpBackendPolicyDefinition := .Values.gcpBackendPolicies.items }}
{{- if hasKey $seen $gcpBackendPolicyDefinition.name }}
{{- fail (printf "GCPBackendPolicy names must be unique: '%s' is duplicated" $gcpBackendPolicyDefinition.name) }}
{{- end }}
{{- $_ := set $seen $gcpBackendPolicyDefinition.name true }}
{{- end }}
{{- $labels := include "gatewayapi.labels" . }}
{{- $commonName := include "gatewayapi.name" . }}
{{- range $gcpBackendPolicyDefinition := .Values.gcpBackendPolicies.items }}
{{- if (ne $gcpBackendPolicyDefinition.enabled false) }}
---
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  {{- $userAnnotations := dig "metadata" "annotations" dict $gcpBackendPolicyDefinition }}
  {{- $defaultAnnotations := dig "default" "metadata" "annotations" dict $.Values.gcpBackendPolicies }}
  {{- if or $userAnnotations $defaultAnnotations }}
  annotations:
    {{- range $k, $v := $defaultAnnotations }}
    {{- if not (hasKey $userAnnotations $k) }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- end }}
    {{- with $userAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- $labels | nindent 4 }}
  name: {{ $gcpBackendPolicyDefinition.name }}
spec:
{{- if and $gcpBackendPolicyDefinition.spec $gcpBackendPolicyDefinition.rawSpec }}
  {{- toYaml $gcpBackendPolicyDefinition.spec | nindent 2 }}
{{- else }}
  default:
    connectionDraining:
      drainingTimeoutSec: {{ dig "default" "connectionDraining" "drainingTimeoutSec" $.Values.gcpBackendPolicies.default.spec.default.connectionDraining.drainingTimeoutSec $gcpBackendPolicyDefinition.spec }}
    timeoutSec: {{ dig "default" "timeoutSec" $.Values.gcpBackendPolicies.default.spec.default.timeoutSec $gcpBackendPolicyDefinition.spec }}
    logging:
      enabled: {{ dig "default" "logging" "enabled" $.Values.gcpBackendPolicies.default.spec.default.logging.enabled $gcpBackendPolicyDefinition.spec }}
  targetRef:
    group: {{ $gcpBackendPolicyDefinition.spec.targetRef.group | default $.Values.gcpBackendPolicies.default.spec.targetRef.group | quote }}
    kind: {{ $gcpBackendPolicyDefinition.spec.targetRef.kind | default $.Values.gcpBackendPolicies.default.spec.targetRef.kind }}
    name: {{ $gcpBackendPolicyDefinition.spec.targetRef.name }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
