{{- if .Values.enabled }}
{{- $seen := dict }}
{{- range $healthCheckPolicyDefinition := .Values.healthCheckPolicies }}
{{- if hasKey $seen $healthCheckPolicyDefinition.name }}
{{- fail (printf "HealthCheckPolicy names must be unique: '%s' is duplicated" $healthCheckPolicyDefinition.name) }}
{{- end }}
{{- $_ := set $seen $healthCheckPolicyDefinition.name true }}
{{- end }}
{{- $labels := include "gatewayapi.labels" . }}
{{- $commonName := include "gatewayapi.name" . }}
{{- range $healthCheckPolicyDefinition := .Values.healthCheckPolicies }}
{{- if (ne $healthCheckPolicyDefinition.enabled false) }}
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  labels:
    {{- $labels | nindent 4 }}
  name: {{ $commonName }}-{{ $healthCheckPolicyDefinition.name }}
spec:
{{- if and $healthCheckPolicyDefinition.spec $healthCheckPolicyDefinition.rawSpec }}
  {{- toYaml $healthCheckPolicyDefinition.spec | nindent 2 }}
{{- else }}
  default:
    config:
      httpHealthCheck:
        port: {{ $healthCheckPolicyDefinition.spec.default.config.httpHealthCheck.port }}
        requestPath: {{ $healthCheckPolicyDefinition.spec.default.config.httpHealthCheck.requestPath }}
      type: {{ $healthCheckPolicyDefinition.spec.default.config.type | default "HTTP" }}
    logConfig:
      enabled: {{ dig "logConfig" "enabled" true $healthCheckPolicyDefinition.spec.default }}
    checkIntervalSec: {{ $healthCheckPolicyDefinition.spec.default.checkIntervalSec | default 5 }}
    timeoutSec: {{ $healthCheckPolicyDefinition.spec.default.timeoutSec | default 1 }}
    healthyThreshold: {{ $healthCheckPolicyDefinition.spec.default.healthyThreshold | default 2 }}
    unhealthyThreshold: {{ $healthCheckPolicyDefinition.spec.default.unhealthyThreshold | default 2 }}
  targetRef:
    group: {{ $healthCheckPolicyDefinition.spec.targetRef.group | default "" | quote }}
    kind: {{ $healthCheckPolicyDefinition.spec.targetRef.kind | default "Service" }}
    name: {{ $healthCheckPolicyDefinition.spec.targetRef.name }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
