{{- range $name, $pc := .Values.proxyClasses }}
{{- if $pc.podDisruptionBudget }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $name }}
spec:
  selector:
    matchLabels:
      proxy-class: {{ $name }}
  {{- toYaml $pc.podDisruptionBudget | nindent 2 }}
{{- end }}
{{- end }}
