{{- range $name, $pc := .Values.proxyClasses }}
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: {{ $name }}
spec:
  statefulSet:
    pod:
      labels:
        app: {{ $name }}
      {{- if $pc.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- range $pc.topologySpreadConstraints }}
        - labelSelector:
            matchLabels:
              app: {{ $name }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if $pc.resources }}
      tailscaleContainer:
        resources:
          {{- toYaml $pc.resources | nindent 10 }}
      {{- end }}
{{- end }}
