name: Test

on:
  push:
    branches:
      - "SRE-4576/gh-pages"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Github Actor
        run: |
          echo "$GITHUB_ACTOR"
