name: Helm Unit Tests

on:
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Helm
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1

      - name: Install helm-unittest
        run: helm plugin install https://github.com/helm-unittest/helm-unittest --version v1.1.2 --verify=false # resolves to 33c48cac798e465deda9a66c8e6c07c0973cf53d

      - name: Run Helm Unit Tests
        run: make test
