# This schema is still a work in progress.
# We are just validating the top-level structure of the ingress configuration.

$schema: "http://json-schema.org/draft-07/schema#"
type: object
definitions: {}
properties:
  ingress:
    type: object
    properties:
      enabled:
        type: boolean
        default: false
      hosts:
        type: array
        items:
          type: object
          properties: {}
        default: []
      tls:
        type: array
        items:
          type: object
          properties: {}
        default: []

    additionalProperties: false
