$schema: "http://json-schema.org/draft-07/schema#"
type: object
properties:
  initContainer:
    type: object
    properties:
      enabled:
        type: boolean
        default: false
      name:
        type: string
      image:
        type: string
      command:
        type: array
        items:
          type: string

    # Validate required fields only if enabled is true
    if:
      properties:
        enabled:
          const: true
    then:
      required:
        - name
        - image
        - command
